# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(1200, 900)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1200, 900))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.main)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 120, 1161, 771))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_layout_line_text = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_layout_line_text.setContentsMargins(0, 0, 0, 0)
        self.grid_layout_line_text.setHorizontalSpacing(50)
        self.grid_layout_line_text.setVerticalSpacing(10)
        self.grid_layout_line_text.setObjectName("grid_layout_line_text")
        self.line_edit_length_step = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_length_step.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_length_step.setFont(font)
        self.line_edit_length_step.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_length_step.setObjectName("line_edit_length_step")
        self.grid_layout_line_text.addWidget(self.line_edit_length_step, 3, 1, 1, 1)
        self.line_edit_initial_temperature = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_initial_temperature.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_initial_temperature.setFont(font)
        self.line_edit_initial_temperature.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_initial_temperature.setObjectName("line_edit_initial_temperature")
        self.grid_layout_line_text.addWidget(self.line_edit_initial_temperature, 1, 0, 1, 1)
        self.line_edit_reactor_parameters = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_reactor_parameters.sizePolicy().hasHeightForWidth())
        self.line_edit_reactor_parameters.setSizePolicy(sizePolicy)
        self.line_edit_reactor_parameters.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_reactor_parameters.setFont(font)
        self.line_edit_reactor_parameters.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_reactor_parameters.setObjectName("line_edit_reactor_parameters")
        self.grid_layout_line_text.addWidget(self.line_edit_reactor_parameters, 0, 0, 1, 1)
        self.line_edit_temperatur_walls = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_temperatur_walls.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_temperatur_walls.setFont(font)
        self.line_edit_temperatur_walls.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_temperatur_walls.setObjectName("line_edit_temperatur_walls")
        self.grid_layout_line_text.addWidget(self.line_edit_temperatur_walls, 2, 0, 1, 1)
        self.line_edit_time_step = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_time_step.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_time_step.setFont(font)
        self.line_edit_time_step.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_time_step.setObjectName("line_edit_time_step")
        self.grid_layout_line_text.addWidget(self.line_edit_time_step, 2, 1, 1, 1)
        self.line_edit_density = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_density.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_density.setFont(font)
        self.line_edit_density.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_density.setObjectName("line_edit_density")
        self.grid_layout_line_text.addWidget(self.line_edit_density, 3, 0, 1, 1)
        self.line_edit_heat_capacity = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_heat_capacity.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_heat_capacity.setFont(font)
        self.line_edit_heat_capacity.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_heat_capacity.setObjectName("line_edit_heat_capacity")
        self.grid_layout_line_text.addWidget(self.line_edit_heat_capacity, 0, 1, 1, 1)
        self.line_edit_humidity = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_humidity.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_humidity.setFont(font)
        self.line_edit_humidity.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_humidity.setObjectName("line_edit_humidity")
        self.grid_layout_line_text.addWidget(self.line_edit_humidity, 1, 1, 1, 1)
        self.line_edit_total_time = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.line_edit_total_time.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_edit_total_time.setFont(font)
        self.line_edit_total_time.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.line_edit_total_time.setObjectName("line_edit_total_time")
        self.grid_layout_line_text.addWidget(self.line_edit_total_time, 4, 0, 1, 1)
        self.push_button_simulate = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.push_button_simulate.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_simulate.setFont(font)
        self.push_button_simulate.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #0055ff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #0049de;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #0044cc;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_simulate.setObjectName("push_button_simulate")
        self.grid_layout_line_text.addWidget(self.push_button_simulate, 4, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.main)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 600, 120))
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: none;\n"
"border-bottom-right-radius: 15px;\n"
"horizontal-aligment: center;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.push_button_0 = QtWidgets.QPushButton(self.frame_2)
        self.push_button_0.setEnabled(True)
        self.push_button_0.setGeometry(QtCore.QRect(40, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_0.setFont(font)
        self.push_button_0.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 12px;\n"
"    color: #0055ff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #ebebeb;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #cdcdcd;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_0.setObjectName("push_button_0")
        self.push_button_window_results = QtWidgets.QPushButton(self.frame_2)
        self.push_button_window_results.setGeometry(QtCore.QRect(320, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.push_button_window_results.setFont(font)
        self.push_button_window_results.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 12px;\n"
"    color: #0055ff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #ebebeb;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #cdcdcd;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_window_results.setObjectName("push_button_window_results")
        self.label_9 = QtWidgets.QLabel(self.main)
        self.label_9.setGeometry(QtCore.QRect(680, 30, 471, 71))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #0055ff;")
        self.label_9.setObjectName("label_9")
        self.label_notification = QtWidgets.QLabel(self.main)
        self.label_notification.setGeometry(QtCore.QRect(220, 70, 701, 91))
        self.label_notification.setText("")
        self.label_notification.setObjectName("label_notification")
        self.label_notification.hide()
        self.stackedWidget.addWidget(self.main)
        self.results = QtWidgets.QWidget()
        self.results.setObjectName("results")
        self.frame_3 = QtWidgets.QFrame(self.results)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 600, 120))
        self.frame_3.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: none;\n"
"border-bottom-right-radius: 15px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.push_button_window_calculation = QtWidgets.QPushButton(self.frame_3)
        self.push_button_window_calculation.setEnabled(True)
        self.push_button_window_calculation.setGeometry(QtCore.QRect(40, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_window_calculation.setFont(font)
        self.push_button_window_calculation.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 12px;\n"
"    color: #0055ff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #ebebeb;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #cdcdcd;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_window_calculation.setObjectName("push_button_window_calculation")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_1.setGeometry(QtCore.QRect(320, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 12px;\n"
"    color: #0055ff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #ebebeb;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #cdcdcd;\n"
"        transform: scale(0.95);\n"
"    }")
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.results)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(85, 801, 1031, 82))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.push_button_import_temperature_distribution_csv = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.push_button_import_temperature_distribution_csv.setEnabled(True)
        self.push_button_import_temperature_distribution_csv.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_import_temperature_distribution_csv.setFont(font)
        self.push_button_import_temperature_distribution_csv.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #0055ff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #0049de;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #0044cc;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_import_temperature_distribution_csv.setObjectName("push_button_import_temperature_distribution_csv")
        self.horizontalLayout_2.addWidget(self.push_button_import_temperature_distribution_csv)
        self.push_button_import_energy_data_csv = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.push_button_import_energy_data_csv.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_button_import_energy_data_csv.sizePolicy().hasHeightForWidth())
        self.push_button_import_energy_data_csv.setSizePolicy(sizePolicy)
        self.push_button_import_energy_data_csv.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_import_energy_data_csv.setFont(font)
        self.push_button_import_energy_data_csv.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #0055ff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #0049de;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #0044cc;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_import_energy_data_csv.setObjectName("push_button_import_energy_data_csv")
        self.horizontalLayout_2.addWidget(self.push_button_import_energy_data_csv)
        self.push_button_import_all_xlsx = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.push_button_import_all_xlsx.setEnabled(True)
        self.push_button_import_all_xlsx.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_import_all_xlsx.setFont(font)
        self.push_button_import_all_xlsx.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #0055ff;\n"
"    width: 238px;\n"
"    height: 67px;\n"
"    border-radius: 10px;\n"
"    color: #ffffff;\n"
"}\n"
"    QPushButton:hover {\n"
"        background-color: #0049de;\n"
"        transform: scale(1.05);\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #0044cc;\n"
"        transform: scale(0.95);\n"
"    }")
        self.push_button_import_all_xlsx.setObjectName("push_button_import_all_xlsx")
        self.horizontalLayout_2.addWidget(self.push_button_import_all_xlsx)
        self.gridLayoutWidget = QtWidgets.QWidget(self.results)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 120, 551, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_temperature_distribution_walls = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_temperature_distribution_walls.setFont(font)
        self.label_temperature_distribution_walls.setText("")
        self.label_temperature_distribution_walls.setObjectName("label_temperature_distribution_walls")
        self.gridLayout.addWidget(self.label_temperature_distribution_walls, 0, 1, 1, 1)
        self.label_accumulated_thermal_energy = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_accumulated_thermal_energy.setFont(font)
        self.label_accumulated_thermal_energy.setText("")
        self.label_accumulated_thermal_energy.setObjectName("label_accumulated_thermal_energy")
        self.gridLayout.addWidget(self.label_accumulated_thermal_energy, 2, 1, 1, 1)
        self.label_cop_base_heating = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_cop_base_heating.setFont(font)
        self.label_cop_base_heating.setText("")
        self.label_cop_base_heating.setObjectName("label_cop_base_heating")
        self.gridLayout.addWidget(self.label_cop_base_heating, 3, 1, 1, 1)
        self.label_temperature_distribution_middle = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_temperature_distribution_middle.setFont(font)
        self.label_temperature_distribution_middle.setText("")
        self.label_temperature_distribution_middle.setObjectName("label_temperature_distribution_middle")
        self.gridLayout.addWidget(self.label_temperature_distribution_middle, 1, 1, 1, 1)
        self.graph_temperature_profiles = QtWidgets.QWidget(self.results)
        self.graph_temperature_profiles.setGeometry(QtCore.QRect(610, 410, 581, 381))
        self.graph_temperature_profiles.setObjectName("graph_temperature_profiles")
        self.graph_temperature_change = QtWidgets.QWidget(self.results)
        self.graph_temperature_change.setGeometry(QtCore.QRect(10, 410, 591, 381))
        self.graph_temperature_change.setObjectName("graph_temperature_change")
        self.graph_thermal_energy = QtWidgets.QWidget(self.results)
        self.graph_thermal_energy.setGeometry(QtCore.QRect(610, 60, 581, 331))
        self.graph_thermal_energy.setObjectName("graph_thermal_energy")
        self.stackedWidget.addWidget(self.results)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.line_edit_length_step.setPlaceholderText(_translate("MainWindow", "Шаг по длине (dx в метрах)"))
        self.line_edit_initial_temperature.setPlaceholderText(_translate("MainWindow", "Начальная температура"))
        self.line_edit_reactor_parameters.setPlaceholderText(_translate("MainWindow", "Параметры реактора (длинна в метрах)"))
        self.line_edit_temperatur_walls.setPlaceholderText(_translate("MainWindow", "Температура стенки"))
        self.line_edit_time_step.setPlaceholderText(_translate("MainWindow", "Шаг по времени (dt в секундах)"))
        self.line_edit_density.setPlaceholderText(_translate("MainWindow", "Плотность (ρ в кг/м³)"))
        self.line_edit_heat_capacity.setPlaceholderText(_translate("MainWindow", "Удельная теплоемкость (Cp в Дж/(кг·K))"))
        self.line_edit_humidity.setPlaceholderText(_translate("MainWindow", "Влажность (H в %)"))
        self.line_edit_total_time.setPlaceholderText(_translate("MainWindow", "Общее время моделирования (в секундах)"))
        self.push_button_simulate.setText(_translate("MainWindow", "Смоделировать"))
        self.frame_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.push_button_0.setText(_translate("MainWindow", "Рассчеты"))
        self.push_button_window_results.setText(_translate("MainWindow", "Результаты"))
        self.label_9.setText(_translate("MainWindow", "BioGas NormLab"))
        self.push_button_window_calculation.setText(_translate("MainWindow", "Рассчеты"))
        self.pushButton_1.setText(_translate("MainWindow", "Результаты"))
        self.push_button_import_temperature_distribution_csv.setText(_translate("MainWindow", "Загрузить температурное \n"
"распределение в файл .csv"))
        self.push_button_import_energy_data_csv.setText(_translate("MainWindow", "Загрузить данные\n"
"по энергии в файл .csv"))
        self.push_button_import_all_xlsx.setText(_translate("MainWindow", "Загрузить все в файл .xlsx"))
        self.label_2.setText(_translate("MainWindow", "Температурное распределение\n"
"по длине реактора во времени (в середине)."))
        self.label.setText(_translate("MainWindow", "Температурное распределение\n"
"по длине реактора во времени (у стенок)."))
        self.label_4.setText(_translate("MainWindow", "Расчет приближенного КПД системы\n"
"по отношению к базовому нагреву."))
        self.label_3.setText(_translate("MainWindow", "Расчет аккумулированной\n"
"тепловой энергии в системе."))
