from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 900)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1200, 900))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.main)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 120, 1121, 541))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(50)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_19.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 1, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_20.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_3.addWidget(self.lineEdit_20, 3, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_21.sizePolicy().hasHeightForWidth())
        self.lineEdit_21.setSizePolicy(sizePolicy)
        self.lineEdit_21.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_3.addWidget(self.lineEdit_21, 0, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_22.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_3.addWidget(self.lineEdit_22, 2, 1, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_23.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_3.addWidget(self.lineEdit_23, 0, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_24.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_3.addWidget(self.lineEdit_24, 2, 0, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_25.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_3.addWidget(self.lineEdit_25, 1, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_26.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_3.addWidget(self.lineEdit_26, 3, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.main)
        self.lineEdit_27.setGeometry(QtCore.QRect(330, 660, 541, 60))
        self.lineEdit_27.setMinimumSize(QtCore.QSize(480, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setStyleSheet("background-color: #f9f9f9;\n"
"width: 500;\n"
"border-radius: 10px;      ")
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.frame_2 = QtWidgets.QFrame(self.main)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 600, 120))
        self.frame_2.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: none;\n"
"border-bottom-right-radius: 15px;\n"
"horizontal-aligment: center;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setEnabled(True)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: #ffffff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 12px;\n"
"color: #0055ff;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(320, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: #ffffff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 12px;\n"
"color: #0055ff;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.main)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 760, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: #0055ff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 10px;\n"
"color: #ffffff;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_9 = QtWidgets.QLabel(self.main)
        self.label_9.setGeometry(QtCore.QRect(680, 30, 471, 71))
        font = QtGui.QFont()
        font.setFamily("Britannic Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: #0055ff;")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.main)
        self.results = QtWidgets.QWidget()
        self.results.setObjectName("results")
        self.frame_3 = QtWidgets.QFrame(self.results)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 600, 120))
        self.frame_3.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"border: none;\n"
"border-bottom-right-radius: 15px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: #ffffff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 12px;\n"
"color: #0055ff;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 30, 238, 67))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: #ffffff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 12px;\n"
"color: #0055ff;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.results)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(85, 801, 1031, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color: #0055ff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 10px;\n"
"color: #ffffff;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color: #0055ff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 10px;\n"
"color: #ffffff;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_2.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color: #0055ff;\n"
"width: 238px;\n"
"height: 67px;\n"
"border-radius: 10px;\n"
"color: #ffffff;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.gridLayoutWidget = QtWidgets.QWidget(self.results)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 140, 571, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.results)
        self.widget_2.setGeometry(QtCore.QRect(610, 430, 581, 361))
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.results)
        self.widget_3.setGeometry(QtCore.QRect(20, 430, 581, 361))
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(self.results)
        self.widget_4.setGeometry(QtCore.QRect(610, 60, 581, 361))
        self.widget_4.setObjectName("widget_4")
        self.stackedWidget.addWidget(self.results)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_19.setPlaceholderText(_translate("MainWindow", "Начальная температура"))
        self.lineEdit_20.setPlaceholderText(_translate("MainWindow", "Шаг по длине (dx в метрах)"))
        self.lineEdit_21.setPlaceholderText(_translate("MainWindow", "Параметры реактора (длинна в метрах)"))
        self.lineEdit_22.setPlaceholderText(_translate("MainWindow", "Шаг по времени (dt в секундах)"))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "Удельная теплоемкость (Cp в Дж/(кг·K))"))
        self.lineEdit_24.setPlaceholderText(_translate("MainWindow", "Температура стенки"))
        self.lineEdit_25.setPlaceholderText(_translate("MainWindow", "Влажность (H в %)"))
        self.lineEdit_26.setPlaceholderText(_translate("MainWindow", "Плотность (ρ в кг/м³)"))
        self.lineEdit_27.setPlaceholderText(_translate("MainWindow", "Общее время моделирования (в секундах)"))
        self.frame_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Рассчеты"))
        self.pushButton_6.setText(_translate("MainWindow", "Результаты"))
        self.pushButton_7.setText(_translate("MainWindow", "Смоделировать"))
        self.label_9.setText(_translate("MainWindow", "BioGas NormLab"))
        self.pushButton_8.setText(_translate("MainWindow", "Рассчеты"))
        self.pushButton_9.setText(_translate("MainWindow", "Результаты"))
        self.pushButton_10.setText(_translate("MainWindow", "Загрузить температурное \n"
"распределение в файл .csv"))
        self.pushButton_12.setText(_translate("MainWindow", "Загрузить данные\n"
"по энергии в файл .csv"))
        self.pushButton_11.setText(_translate("MainWindow", "Загрузить все в файл .xlsx"))
        self.label_2.setText(_translate("MainWindow", "Температурное распределение\n"
"по длине реактора во времени (в середине)."))
        self.label.setText(_translate("MainWindow", "Температурное распределение\n"
"по длине реактора во времени (у стенок)."))
        self.label_4.setText(_translate("MainWindow", "Расчет приближенного КПД системы\n"
"по отношению к базовому нагреву."))
        self.label_3.setText(_translate("MainWindow", "Расчет аккумулированной\n"
"тепловой энергии в системе."))
